#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : uwsgi
Version  : 2.0.11.1
Release  : 1
URL      : http://projects.unbit.it/downloads/uwsgi-2.0.11.1.tar.gz
Source0  : http://projects.unbit.it/downloads/uwsgi-2.0.11.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: uwsgi-bin
Requires: uwsgi-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
The uWSGI project
For official documentation check: https://uwsgi-docs.readthedocs.org/en/latest/

%package bin
Summary: bin components for the uwsgi package.
Group: Binaries

%description bin
bin components for the uwsgi package.


%package python
Summary: python components for the uwsgi package.
Group: Default

%description python
python components for the uwsgi package.


%prep
%setup -q -n uwsgi-2.0.11.1

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/uwsgi

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
